FROM rust:1.84-slim AS builder

WORKDIR /usr/src/app
COPY rust-serverless ./rust-serverless

WORKDIR /usr/src/app/rust-serverless
RUN cargo build --release

# Distroless 'cc' image includes glibc and libgcc, required by standard Rust builds
FROM gcr.io/distroless/cc-debian12:nonroot

WORKDIR /app
COPY --from=builder /usr/src/app/rust-serverless/target/release/rust-serverless /app/rust-serverless
COPY graph.rkyv /app/graph.rkyv

CMD ["./rust-serverless"]

EXPOSE 8080